// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myAPI.Data;

#nullable disable

namespace myAPI.Migrations
{
    [DbContext(typeof(BaseHospital))]
    partial class BaseHospitalModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("myAPI.Models.InternamentoModel", b =>
                {
                    b.Property<int>("InternamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataAlta")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataInt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroAIH")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcedimentoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InternamentoId");

                    b.ToTable("Internamentos");
                });

            modelBuilder.Entity("myAPI.Models.PacienteModel", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataNasc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcedimentoID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sexo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("PacienteId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("myAPI.Models.ProcedimentoModel", b =>
                {
                    b.Property<int>("ProcedimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescProcedimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Medico")
                        .HasColumnType("TEXT");

                    b.Property<int>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QtdProcedimento")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProcedimentoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Procedimentos");
                });

            modelBuilder.Entity("myAPI.Models.ProcedimentoModel", b =>
                {
                    b.HasOne("myAPI.Models.PacienteModel", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
